apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-job-every-quarter
spec:
  schedule: "0,15,30,45 * * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: job
            image: luksa/batch-job
