apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    metadata:
      labels:
        app: example-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job
        image: luksa/batch-job
