apiVersion: v1
kind: Pod
metadata:
    name: fortune
spec:
    containers:
    - image: dsmiech/fortune:args
      args: ["2"]
      name: html-generator
      volumeMounts:
      - name: html
        mountPath: /var/htdocs
    - image: dsmiech/nginx
      name: web-server
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly: true
      ports:
      - containerPort: 80
    volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: fortune-config
        items:
        - key: my-nginx-config.conf
          path: gzip.conf
