apiVersion: v1
kind: Service
metadata:
  name: example-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 21413
    nodePort: 31234 # not necessary
  selector:
    server: monitoring
