apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http
spec:
  replicas: 4
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: http
      labels:
        app: http
    spec:
      containers:
        - image: dsmiech/python_http:v3
          name: python-http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
