apiVersion: v1
kind: ReplicationController
metadata:
  name: http-v1
spec:
  replicas: 4
  template:
    metadata:
      name: http
      labels:
        app: http
    spec:
      containers:
      - image: dsmiech/python_http:v1
        name: python-http
---
apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  type: NodePort
  selector:
    app: http
  ports:
  - port: 8080
    targetPort: 8080
